import { FormFieldConfig, FormFieldType } from '../models/form-config.model';

export const THEME_FORM_CONFIG: Record<string, FormFieldConfig[]> = {
  colors: [
    {
      key: 'primary',
      label: 'Primary Color',
      type: FormFieldType.COLOR,
      description: 'Main brand color',
    },
    {
      key: 'secondary',
      label: 'Secondary Color',
      type: FormFieldType.COLOR,
      description: 'Secondary brand color',
    },
    {
      key: 'success',
      label: 'Success Color',
      type: FormFieldType.COLOR,
      description: 'Success state color',
    },
    {
      key: 'warning',
      label: 'Warning Color',
      type: FormFieldType.COLOR,
      description: 'Warning state color',
    },
    {
      key: 'danger',
      label: 'Danger Color',
      type: FormFieldType.COLOR,
      description: 'Error/danger state color',
    },
    {
      key: 'background',
      label: 'Background',
      type: FormFieldType.COLOR,
      description: 'Main background color',
    },
    {
      key: 'surface',
      label: 'Surface',
      type: FormFieldType.COLOR,
      description: 'Card/surface background',
    },
    {
      key: 'text',
      label: 'Text Color',
      type: FormFieldType.COLOR,
      description: 'Primary text color',
    },
    {
      key: 'textSecondary',
      label: 'Secondary Text',
      type: FormFieldType.COLOR,
      description: 'Secondary text color',
    },
    {
      key: 'border',
      label: 'Border Color',
      type: FormFieldType.COLOR,
      description: 'Default border color',
    },
  ],
  typography: [
    {
      key: 'fontFamily',
      label: 'Font Family',
      type: FormFieldType.TEXT,
      placeholder: 'system-ui, sans-serif',
      description: 'Primary font family',
    },
    {
      key: 'fontFamilyMono',
      label: 'Monospace Font',
      type: FormFieldType.TEXT,
      placeholder: 'monospace',
      description: 'Monospace font for code',
    },
    { key: 'fontSizeXs', label: 'Font Size XS', type: FormFieldType.TEXT, placeholder: '0.75rem' },
    { key: 'fontSizeSm', label: 'Font Size SM', type: FormFieldType.TEXT, placeholder: '0.875rem' },
    { key: 'fontSizeBase', label: 'Font Size Base', type: FormFieldType.TEXT, placeholder: '1rem' },
    { key: 'fontSizeLg', label: 'Font Size LG', type: FormFieldType.TEXT, placeholder: '1.125rem' },
    { key: 'fontSizeXl', label: 'Font Size XL', type: FormFieldType.TEXT, placeholder: '1.25rem' },
    { key: 'fontSize2xl', label: 'Font Size 2XL', type: FormFieldType.TEXT, placeholder: '1.5rem' },
    {
      key: 'fontSize3xl',
      label: 'Font Size 3XL',
      type: FormFieldType.TEXT,
      placeholder: '1.875rem',
    },
    {
      key: 'fontWeightNormal',
      label: 'Weight Normal',
      type: FormFieldType.TEXT,
      placeholder: '400',
    },
    {
      key: 'fontWeightMedium',
      label: 'Weight Medium',
      type: FormFieldType.TEXT,
      placeholder: '500',
    },
    {
      key: 'fontWeightSemibold',
      label: 'Weight Semibold',
      type: FormFieldType.TEXT,
      placeholder: '600',
    },
    { key: 'fontWeightBold', label: 'Weight Bold', type: FormFieldType.TEXT, placeholder: '700' },
    {
      key: 'lineHeightTight',
      label: 'Line Height Tight',
      type: FormFieldType.TEXT,
      placeholder: '1.25',
    },
    {
      key: 'lineHeightNormal',
      label: 'Line Height Normal',
      type: FormFieldType.TEXT,
      placeholder: '1.5',
    },
    {
      key: 'lineHeightRelaxed',
      label: 'Line Height Relaxed',
      type: FormFieldType.TEXT,
      placeholder: '1.75',
    },
  ],
  spacing: [
    { key: 'xs', label: 'Extra Small', type: FormFieldType.TEXT, placeholder: '0.25rem' },
    { key: 'sm', label: 'Small', type: FormFieldType.TEXT, placeholder: '0.5rem' },
    { key: 'md', label: 'Medium', type: FormFieldType.TEXT, placeholder: '1rem' },
    { key: 'lg', label: 'Large', type: FormFieldType.TEXT, placeholder: '1.5rem' },
    { key: 'xl', label: 'Extra Large', type: FormFieldType.TEXT, placeholder: '2rem' },
    { key: '2xl', label: '2X Large', type: FormFieldType.TEXT, placeholder: '3rem' },
    { key: '3xl', label: '3X Large', type: FormFieldType.TEXT, placeholder: '4rem' },
  ],
  radius: [
    { key: 'none', label: 'None', type: FormFieldType.TEXT, placeholder: '0' },
    { key: 'sm', label: 'Small', type: FormFieldType.TEXT, placeholder: '0.25rem' },
    { key: 'md', label: 'Medium', type: FormFieldType.TEXT, placeholder: '0.5rem' },
    { key: 'lg', label: 'Large', type: FormFieldType.TEXT, placeholder: '0.75rem' },
    { key: 'xl', label: 'Extra Large', type: FormFieldType.TEXT, placeholder: '1rem' },
    { key: 'full', label: 'Full', type: FormFieldType.TEXT, placeholder: '9999px' },
  ],
};
